[project]
name = "brent-waste"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "icalendar>=6.3.1",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "pylint>=3.3.7",
]
